language: node_js

node_js:
  - node
  - lts/*

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y zlib1g-dev

script:
  yarn run test && test -z "$(git status --porcelain)"
